### ISSUE TITLE
ChartView Not Defined

### ISSUE THREAD

**Issue by powerteqtpitman** [Steema/TeeChart-NET-Pro-Samples#3]
I am upgrading a project from Xamarin Forms to MAUI.

In my code I have the following:

```
        ChartView _chart;
        _chart = new ChartView();
```

When I open my Xamarin Forms version of the project, this is defined and when I right click go to definition it takes me to the object browser and shows it is defined in the Steema.TeeChart namespace.

In my MAUI version of the project I have added the nuget package for MAUI and use this same code. In the MAUI project I get an error that ChartView is not defined and I can't seem to find it anywhere.

I went to the Gallery example and it has the example same code as above for the MAUI example.

What is going on? Where is ChartView defined and how to I get it into my project?

**Comment by PepJorge** [comment]
Doe sthis happens also in a new clean MAUI project ?

**Comment by powerteqtpitman** [comment]
I was able to fix the issue by adding a TChart to the xaml and then referencing it in the C# code the same way I was referencing the CharView() directly before.

I have not tried this in a new project.
